// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI8pMjq94vrUFEOXQGoRc_QeLNSU5iI1E',
    appId: '1:579615102822:web:d48ec37c58dbc739dedaa7',
    messagingSenderId: '579615102822',
    projectId: 'message-c44ce',
    authDomain: 'message-c44ce.firebaseapp.com',
    storageBucket: 'message-c44ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj9barGWf2yNpjmFPhTs9tahZOv2O1pg4',
    appId: '1:579615102822:android:f470207a8ab5d427dedaa7',
    messagingSenderId: '579615102822',
    projectId: 'message-c44ce',
    storageBucket: 'message-c44ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw7KpQD1fdyDzjAcd6ooTF1KOdGP_ekds',
    appId: '1:579615102822:ios:d696e5c53a0407c3dedaa7',
    messagingSenderId: '579615102822',
    projectId: 'message-c44ce',
    storageBucket: 'message-c44ce.firebasestorage.app',
    iosBundleId: 'com.example.messanger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw7KpQD1fdyDzjAcd6ooTF1KOdGP_ekds',
    appId: '1:579615102822:ios:d696e5c53a0407c3dedaa7',
    messagingSenderId: '579615102822',
    projectId: 'message-c44ce',
    storageBucket: 'message-c44ce.firebasestorage.app',
    iosBundleId: 'com.example.messanger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI8pMjq94vrUFEOXQGoRc_QeLNSU5iI1E',
    appId: '1:579615102822:web:784734cf3af06217dedaa7',
    messagingSenderId: '579615102822',
    projectId: 'message-c44ce',
    authDomain: 'message-c44ce.firebaseapp.com',
    storageBucket: 'message-c44ce.firebasestorage.app',
  );
}
